"""init_knowledge_tables

Revision ID: 01300a7f50fc
Revises: 
Create Date: 2026-07-28 17:09:50.633711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01300a7f50fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_ingest_jobs',
    sa.Column('doc_id', sa.String(length=16), nullable=False, comment='关联 knowledge_docs.doc_id'),
    sa.Column('stage', sa.String(length=20), nullable=False, comment='阶段: parse/chunk/embed/index'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度百分比 0-100'),
    sa.Column('parser', sa.String(length=20), nullable=False, comment='解析器: mineru/llamaindex'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_ingest_jobs_doc_id'), 'doc_ingest_jobs', ['doc_id'], unique=False)
    op.create_table('knowledge_docs',
    sa.Column('doc_id', sa.String(length=16), nullable=False, comment='md5(doc_name)[:16]'),
    sa.Column('doc_name', sa.String(length=255), nullable=False, comment='文档名称'),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='文档类型: repair_manual/spec_doc/tsb/issue_case'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='分类标签'),
    sa.Column('business_line', sa.String(length=50), nullable=True, comment='业务线'),
    sa.Column('model_code', sa.String(length=50), nullable=True, comment='车型代码'),
    sa.Column('minio_key', sa.String(length=500), nullable=True, comment='MinIO 原始文件 key'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='总页数'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='切片数量'),
    sa.Column('chunk_strategy', sa.String(length=20), nullable=True, comment='切片策略: fixed/semantic/parent_child'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: ingesting/indexed/deleted'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_docs_doc_id'), 'knowledge_docs', ['doc_id'], unique=True)
    op.create_table('knowledge_feedback',
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户标识'),
    sa.Column('question', sa.Text(), nullable=False, comment='用户问题'),
    sa.Column('answer_preview', sa.Text(), nullable=True, comment='答案摘要'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='评分: 1 赞 / -1 踩 / 0 中性'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评语'),
    sa.Column('intent', sa.String(length=50), nullable=True, comment='意图分类'),
    sa.Column('channels', sa.String(length=100), nullable=True, comment='使用的检索通道'),
    sa.Column('trace_id', sa.String(length=20), nullable=True, comment='关联请求'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_feedback_user_id'), 'knowledge_feedback', ['user_id'], unique=False)
    op.create_table('knowledge_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_name', sa.String(length=255), nullable=False, comment='文档名称'),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='文档类型'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='分类'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作: upload/update/delete'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_experiments',
    sa.Column('exp_name', sa.String(length=100), nullable=False, comment='实验名称'),
    sa.Column('chunk_strategy', sa.String(length=20), nullable=False, comment='切片策略'),
    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='切片大小'),
    sa.Column('top_k', sa.Integer(), nullable=False, comment='检索 Top-K'),
    sa.Column('rerank_top_k', sa.Integer(), nullable=False, comment='重排 Top-K'),
    sa.Column('use_hyde', sa.Boolean(), nullable=False, comment='启用 HyDE'),
    sa.Column('use_hybrid', sa.Boolean(), nullable=False, comment='启用混合检索'),
    sa.Column('context_relevance', sa.Float(), nullable=True, comment='上下文相关性'),
    sa.Column('groundedness', sa.Float(), nullable=True, comment='有据性'),
    sa.Column('answer_relevance', sa.Float(), nullable=True, comment='答案相关性'),
    sa.Column('safety_score', sa.Float(), nullable=True, comment='安全性评分'),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True, comment='P95 延迟(ms)'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_experiments')
    op.drop_table('knowledge_notifications')
    op.drop_index(op.f('ix_knowledge_feedback_user_id'), table_name='knowledge_feedback')
    op.drop_table('knowledge_feedback')
    op.drop_index(op.f('ix_knowledge_docs_doc_id'), table_name='knowledge_docs')
    op.drop_table('knowledge_docs')
    op.drop_index(op.f('ix_doc_ingest_jobs_doc_id'), table_name='doc_ingest_jobs')
    op.drop_table('doc_ingest_jobs')
    # ### end Alembic commands ###
